config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  
  necker_landing_paths = %w[voter_participation states_xy active_charts]
  
  necker_landing_paths.each do |necker_path|
    get "/#{necker_path}", to: "landing##{necker_path}", as: necker_path
  end
  
  resources :datasheets, only: %i[index show]
  resources :words, only: %i[index]
  
  namespace :admin do
    resources :datasheets, only: %i[index new show create destroy]
  end

  root 'landing#featured'
end

app/views/layouts/_footer.html.erb
<footer>
  <% if admin_signed_in? %>
    <%= link_to "Log out", destroy_admin_session_path, method: :delete %>
  <% elsif controller_name != 'sessions' %>
    <%= link_to "Log in", new_admin_session_path %>
  <% end %>
</footer>

app/views/layouts/_header.html.erb
    <header>
      <h1><%= link_to_unless current_page?(root_path), 'Necker', root_path %></h1>
      <p><%= render partial: 'shared/necker_cube' %></p>
      <p>
        <%= link_to_unless current_page?(root_path), 'Featured Charts', root_path %>
         / <%= link_to_unless current_page?(datasheets_path), 'Auto-Generated Charts', datasheets_path %>
        <% if admin_signed_in? %>
           / <%= link_to_unless current_page?(admin_datasheets_path), 'All Datasheets', admin_datasheets_path %>
           / <%= link_to_unless current_page?(new_admin_datasheet_path), 'Upload CSV', new_admin_datasheet_path %>
        <% end %>
      </p>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Necker</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= favicon_link_tag 'favicon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <div class="flash">
       <p class="notice"><%= tag.span notice if notice %></p>
       <p class="alert"><%= tag.span alert if alert %></p>
    </div>
    <div id="container">
      <%= yield %>
    </div>
    <%= render partial: 'layouts/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/plain.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveCharts - Chart Gallery</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.png' %>
    <%= favicon_link_tag 'favicon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  </head>

  <body>
    <div id="full-container">
      <%= yield %>
    </div>
    <footer>
      <%= yield :footer %>
    </footer>
    <%= javascript_include_tag 'application' %>
  </body>
</html>